#!/bin/bash -x
#SBATCH --account=almagal
#SBATCH --nodes=1
#SBATCH --ntasks=2
#SBATCH --ntasks-per-node=2
#SBATCH --output=mpi-out.%j
#SBATCH --error=mpi-err.%j
#SBATCH --time=ToModifyTIME
#SBATCH --partition=ToModifyMEMORY

./mainScriptForJointDeconvolutionTM2TM1.sh
