#!/bin/bash -x
#SBATCH --account=almagal
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --ntasks-per-node=16
#SBATCH --output=mpi-out.%j
#SBATCH --error=mpi-err.%j
#SBATCH --time=06:00:00
#SBATCH --partition=batch

./mainScriptForImagingTM1_serial.sh
