#!/bin/bash -x
#SBATCH --account=almagal
#SBATCH --nodes=1
#SBATCH --ntasks=12
#SBATCH --ntasks-per-node=12
#SBATCH --output=mpi-out.%j
#SBATCH --error=mpi-err.%j
#SBATCH --time=03:00:00
#SBATCH --partition=mem192

./mainScriptForImagingTM1.sh
